apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tiphys
  description: Tiphys - the engine that facilitates "Github Deployment Driven GitOps" at ThousandEyes
  labels:
    product: cicd
  annotations:
    github.com/project-slug: thousandeyes/tiphys
    github.com/team-slug: thousandeyes/engineering-effectiveness
    backstage.io/techdocs-ref: dir:.
    argocd/app-selector: application-name=tiphys-server
  tags:
    - go
    - backend
    - gitops
spec:
  type: service
  lifecycle: production
  owner: engineering-effectiveness
